version: '3.4'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - /var/www/certbot:/var/www/certbot/:ro
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
      - ./nostr:/nostr:ro
    network_mode: host
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  gitea:
    image: docker.io/gitea/gitea:nightly
    container_name: gitea
    restart: always
    environment:
      DISABLE_REGISTRATION: true # change to true for first installation
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6177:3000"
      - "2233:22"
  relay:
    image: satstralia/satstralia-web-nostr:0.1
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./relay/onion_urls.txt:/app/onion_urls.txt:ro
      - ./relay/config/strfry.conf:/etc/strfry.conf:ro
      - ./relay/db:/app/strfry-db:rw
  tor:
    build: ./tor
    restart: always
    network_mode: host
    volumes:
      - ./tor/data:/var/lib/tor
      - ./tor/torrc:/etc/tor/torrc
  onionbalance:
    build: ./onionbalance
    restart: always
    network_mode: host
    volumes:
      - ./onionbalance/config:/etc/onionbalance:ro
      - ./onionbalance/data:/var/lib/onionbalance
      - ./tor/data:/var/lib/tor:ro
    depends_on:
      - tor
  certbot:
    image: certbot/certbot:latest
    restart: always
    volumes:
      - /var/www/certbot/:/var/www/certbot/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

